services:
  - type: web
    name: earthquake-tracker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m gunicorn app:app --bind 0.0.0.0:$PORT"
    plan: free